project_id = "sfpqxrlvcapusldvaxsx"

[functions.generate-pix]
verify_jwt = false

[functions.get-pixel-config]
verify_jwt = false

[functions.get-popup-model]
verify_jwt = false

[functions.pix-webhook]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.verify-reset-code]
verify_jwt = false
